name: Generate PDF to release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Generate PDF to release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Checkout source
        uses: actions/checkout@v2

      - name: Generate PDF
        run: npm run pdf

      - name: Upload & Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: resume.pdf
          tag: ${{ github.ref }}
          overwrite: true
